/**
 * Error Codes
 *
 * WHERE: API throws via AppError. Dashboard reads code for UI.
 * SHAPE: { error: { code: 'EMAIL_EXISTS', message: '...' } }
 */

const ERROR_CODES = {
  // Auth (401, 409)
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_REFRESH: 'INVALID_REFRESH',

  // API key + profile (401, 403, 429)
  INVALID_API_KEY: 'INVALID_API_KEY',
  INVALID_PROFILE: 'INVALID_PROFILE',
  PROFILE_LIMIT: 'PROFILE_LIMIT',

  // Leads (403)
  LEAD_LIMIT: 'LEAD_LIMIT',

  // Credits (402)
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  JOB_ALREADY_RUNNING: 'JOB_ALREADY_RUNNING',

  // Enrichment (502, 403)
  ENRICHMENT_FAILED: 'ENRICHMENT_FAILED',
  INVALID_CALLBACK: 'INVALID_CALLBACK',

  // General (400, 404, 429, 426, 500)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  VERSION_OUTDATED: 'VERSION_OUTDATED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = { ERROR_CODES };
